### ISSUE TITLE
∆ Quote Font Style & Responsiveness

### ISSUE THREAD

**Issue by joshacross** [JohnBanas/motivation-manager#20]
• Change quote style away from cursive to a mono, sans script italic font to be more legible
• Make the font responsive 
![Screen Shot 2021-03-30 at 11 26 18 PM](https://user-images.githubusercontent.com/74011006/113090442-5d90b100-91af-11eb-8512-d78b927d34fb.png)

**Comment by chill-phil** [comment]
Complete
