### ISSUE TITLE
BUG: All fields need to be required**

### ISSUE THREAD

**Issue by joshacross** [JohnBanas/motivation-manager#26]
Add in the modal that all tasks need to be required 

read through docs on jQuery on adding attribute of required field
![Screen Shot 2021-03-30 at 11 39 27 PM](https://user-images.githubusercontent.com/74011006/113091267-333ff300-91b1-11eb-9c71-65ee1c3fc1e7.png)

**Comment by joshacross** [comment]
In foundation - https://get.foundation/sites/docs/abide.html#undefined

Need to make title and date a required field.

If required, browser should notify user that it is required. @carrington13

**Comment by carrington13** [comment]
Currently has basic function. Still need to add some kind of alert to the user.
