### ISSUE TITLE
Future: Enhancement: Make Add Task Sticky

### ISSUE THREAD

**Issue by joshacross** [JohnBanas/motivation-manager#29]
Make the add task button stick to the page on scroll 
![Screen Shot 2021-03-30 at 11 43 28 PM](https://user-images.githubusercontent.com/74011006/113091535-bfeab100-91b1-11eb-85c3-f9f628470822.png)

**Comment by JohnBanas** [comment]
Instead of making the add task sticky, since Josh already created another create task button on the navigation, I made the navigation sticky and responsive.
