### ISSUE TITLE
Future: Add list item underneath notes text box & make it editable

### ISSUE THREAD

**Issue by joshacross** [JohnBanas/motivation-manager#32]
Add a list item underneath the notes text box & make it editable 

![Screen Shot 2021-03-30 at 11 46 55 PM](https://user-images.githubusercontent.com/74011006/113091771-41424380-91b2-11eb-89eb-2cc7857badc0.png)

**Comment by carrington13** [comment]
Functionality is more-or-less done, but needs to be beautified and optimized/simplified for use
