### ISSUE TITLE
Future: Add buttons to grateful/meetings/tasks

### ISSUE THREAD

**Issue by joshacross** [JohnBanas/motivation-manager#33]
Add buttons to Grateful/Meetings/Tasks 

It may be easy to just add the same tag with an icon instead of Add Task (located at the bottom) 

![Screen Shot 2021-03-30 at 11 49 52 PM](https://user-images.githubusercontent.com/74011006/113091952-a433da80-91b2-11eb-9112-dc5ce64dc373.png)

**Comment by JohnBanas** [comment]
we have two add buttons already, and we are going to go with a sticky nav bar which will have an add task on it. This will allow additional tasks and grateful items etc. also with the edit function it will pretty much take care of this issue need.
