### ISSUE TITLE
Finalize HTML

### ISSUE THREAD

**Issue by carrington13** [JohnBanas/motivation-manager#4]
Complete and finalize All HTML to streamline CSS coding

**Comment by joshacross** [comment]
Feature: 
Title: Finalize HTML - 
Add Modal section - Selectors available - Change big 3 to tasks
Add grateful, radar, Study, - dropdown menu - 
5 across the top - Above title

Add elements to the modal -

**Comment by joshacross** [comment]
Add on Navigation dropdown menu
